version: '3.3'
services:
  db:
    image: amd64/mysql:oracle
    ports:
      - "3307:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_DATABASE=softuni_mobilele_sec
      - MYSQL_ROOT_PASSWORD=root
      
  mobilele:
    image: kalin98/mobilele:v1
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=root

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui%