logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/softuni_mobilele_sec?useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:1025}
  username: ${MAIL_USERNAME:admin@example.com}
  password: ${MAIL_PASS:}
 
